import asyncio
import json

import uvicorn
from fastapi import FastAPI
from starlette.middleware.cors import CORSMiddleware
from starlette_context.middleware import RawContextMiddleware

from src.controllers.betting_api import router as BettingAPIRouter
from src.controllers.collateral_api import router as CollateralAPIRouter
from src.controllers.feedback_api import router as FeedbackAPIRouter
from src.controllers.todays_api import router as TodaysAPIRouter
from src.helpers.sql_db import get_db
from src.middlewares.db_session import DBSessionMiddleware

API_PREFIX_V1 = "/racing-api/api/v1"


def create_app() -> FastAPI:
    openapi_url = "/users-api/openapi.json"
    docs_url = "/users-api/docs"
    app = FastAPI(
        title="Users - OpenAPI 3.0",
        description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
        version="0.1.0",
        openapi_url=openapi_url,
        docs_url=docs_url,
    )

    app.add_middleware(RawContextMiddleware)
    app.add_middleware(DBSessionMiddleware)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],  # List the URL(s) of your frontend app
        allow_credentials=True,
        allow_methods=[
            "GET",
            "POST",
        ],  # Or specify just the methods you need: ['GET', 'POST', etc.]
        allow_headers=["*"],  # Or specify just the headers you need
    )
    app.include_router(FeedbackAPIRouter, prefix=API_PREFIX_V1)
    app.include_router(TodaysAPIRouter, prefix=API_PREFIX_V1)
    app.include_router(CollateralAPIRouter, prefix=API_PREFIX_V1)
    app.include_router(BettingAPIRouter, prefix=API_PREFIX_V1)
    return app


def get_betting_session_id():
    db = get_db()
    data = db.fetch_data(
        "SELECT MAX(session_id) as session_id FROM betting.selections_info"
    )
    session_id = data["session_id"].max()
    with open("betting_session.json", "w") as f:
        json.dump({"session_id": str(session_id)}, f)


async def main():
    return create_app()


if __name__ == "__main__":
    get_betting_session_id()
    app = asyncio.run(main())
    uvicorn.run(app, host="0.0.0.0", port=8000)
