from datetime import datetime
from sqlalchemy import DateTime, Float, Integer, String
from sqlalchemy.orm import Mapped, declarative_base, mapped_column

Base = declarative_base()

class PerformanceData(Base):
    __tablename__ = "unioned_performance_data"

    horse_name: Mapped[str] = mapped_column(String(132), nullable=False)
    age: Mapped[int] = mapped_column(Integer, nullable=False)
    horse_sex: Mapped[str] = mapped_column(String(32), nullable=False)
    draw: Mapped[int] = mapped_column(Integer, nullable=False)
    headgear: Mapped[str] = mapped_column(String(64), nullable=False)
    weight_carried: Mapped[str] = mapped_column(String(16), nullable=False)
    weight_carried_lbs: Mapped[int] = mapped_column(Integer, nullable=False)
    extra_weight: Mapped[int] = mapped_column(Integer, nullable=False)
    jockey_claim: Mapped[int] = mapped_column(Integer, nullable=False)
    finishing_position: Mapped[str] = mapped_column(String(6), nullable=False)
    total_distance_beaten: Mapped[float] = mapped_column(Float, nullable=False)
    industry_sp: Mapped[str] = mapped_column(String(16), nullable=False)
    betfair_win_sp: Mapped[float] = mapped_column(Float, nullable=False)
    betfair_place_sp: Mapped[float] = mapped_column(Float, nullable=False)
    official_rating: Mapped[int] = mapped_column(Integer, nullable=False)
    ts: Mapped[int] = mapped_column(Integer, nullable=False)
    rpr: Mapped[int] = mapped_column(Integer, nullable=False)
    tfr: Mapped[int] = mapped_column(Integer, nullable=False)
    tfig: Mapped[int] = mapped_column(Integer, nullable=False)
    in_play_high: Mapped[float] = mapped_column(Float, nullable=False)
    in_play_low: Mapped[float] = mapped_column(Float, nullable=False)
    in_race_comment: Mapped[str] = mapped_column(String, nullable=False)
    tf_comment: Mapped[str] = mapped_column(String, nullable=False)
    tfr_view: Mapped[str] = mapped_column(String(16), nullable=False)
    race_id: Mapped[int] = mapped_column(Integer, nullable=False)
    horse_id: Mapped[int] = mapped_column(Integer, nullable=False)
    jockey_id: Mapped[int] = mapped_column(Integer, nullable=False)
    trainer_id: Mapped[int] = mapped_column(Integer, nullable=False)
    owner_id: Mapped[int] = mapped_column(Integer, nullable=False)
    sire_id: Mapped[int] = mapped_column(Integer, nullable=False)
    dam_id: Mapped[int] = mapped_column(Integer, nullable=False)
    unique_id: Mapped[str] = mapped_column(String(132), nullable=False)
    race_time: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    race_date: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    race_title: Mapped[str] = mapped_column(String(132), nullable=False)
    race_type: Mapped[str] = mapped_column(String(32), nullable=False)
    race_class: Mapped[int] = mapped_column(Integer, nullable=False)
    distance: Mapped[str] = mapped_column(String(16), nullable=False)
    distance_yards: Mapped[float] = mapped_column(Float, nullable=False)
    distance_meters: Mapped[float] = mapped_column(Float, nullable=False)
    distance_kilometers: Mapped[float] = mapped_column(Float, nullable=False)
    conditions: Mapped[str] = mapped_column(String(32), nullable=False)
    going: Mapped[str] = mapped_column(String(32), nullable=False)
    number_of_runners: Mapped[int] = mapped_column(Integer, nullable=False)
    hcap_range: Mapped[str] = mapped_column(String(32), nullable=False)
    age_range: Mapped[str] = mapped_column(String(32), nullable=False)
    surface: Mapped[str] = mapped_column(String(32), nullable=False)
    total_prize_money: Mapped[int] = mapped_column(Integer, nullable=False)
    first_place_prize_money: Mapped[int] = mapped_column(Integer, nullable=False)
    winning_time: Mapped[str] = mapped_column(String(32), nullable=False)
    time_seconds: Mapped[float] = mapped_column(Float, nullable=False)
    relative_time: Mapped[float] = mapped_column(Float, nullable=False)
    relative_to_standard: Mapped[str] = mapped_column(String(16), nullable=False)
    country: Mapped[str] = mapped_column(String(64), nullable=False)
    main_race_comment: Mapped[str] = mapped_column(String, nullable=False)
    meeting_id: Mapped[str] = mapped_column(String(132), nullable=False)
    course_id: Mapped[int] = mapped_column(Integer, nullable=False)
    course: Mapped[str] = mapped_column(String(132), nullable=False)
    dam: Mapped[str] = mapped_column(String(132), nullable=False)
    sire: Mapped[str] = mapped_column(String(132), nullable=False)
    trainer: Mapped[str] = mapped_column(String(132), nullable=False)
    jockey: Mapped[str] = mapped_column(String(132), nullable=False)
