from datetime import date, datetime
from src.models.base_entity import BaseEntity

class TodaysRacesResponse(BaseEntity):
    race_id: int
    race_time: datetime
    race_date: date
    race_title: str
    race_type: str
    race_class: int
    distance: str
    distance_yards: float
    distance_meters: float
    distance_kilometers: float
    conditions: str
    going: str
    number_of_runners: int
    hcap_range: str
    age_range: str
    surface: str
    total_prize_money: int
    first_place_prize_money: int
    course_id: int
    course: str
    data_type: str


class TodaysPerformanceDataResponse(BaseEntity):
    horse_name: str
    age: int
    horse_sex: str
    draw: int
    headgear: str
    weight_carried: str
    weight_carried_lbs: int
    extra_weight: int
    jockey_claim: int
    finishing_position: str
    total_distance_beaten: float
    industry_sp: str
    betfair_win_sp: float
    betfair_place_sp: float
    official_rating: int
    ts: int
    rpr: int
    tfr: int
    tfig: int
    in_play_high: float
    in_play_low: float
    in_race_comment: str
    tf_comment: str
    tfr_view: str
    race_id: int
    horse_id: int
    jockey_id: int
    trainer_id: int
    owner_id: int
    sire_id: int
    dam_id: int
    unique_id: str
    race_time: datetime
    race_date: date
    race_title: str
    race_type: str
    race_class: int
    distance: str
    distance_yards: float
    distance_meters: float
    distance_kilometers: float
    conditions: str
    going: str
    number_of_runners: int
    hcap_range: str
    age_range: str
    surface: str
    total_prize_money: int
    first_place_prize_money: int
    winning_time: str
    time_seconds: float
    relative_time: float
    relative_to_standard: str
    country: str
    main_race_comment: str
    meeting_id: str
    course_id: int
    course: str
    dam: str
    sire: str
    trainer: str
    jockey: str
    data_type: str
